// Shared styles for the auth pages (login, register, forgot, reset).
// Match the dark theme used elsewhere in the app.

export const A = {
  page: {
    background: "#0a0e1a",
    minHeight:  "100vh",
    display:    "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    color:      "#c8d8e8",
    padding:    "40px 16px",
  },
  card: {
    background:   "#0e1424",
    border:       "1px solid #1d2638",
    borderRadius: "6px",
    padding:      "40px 36px",
    width:        "100%",
    maxWidth:     "480px",
    boxShadow:    "0 12px 32px rgba(0,0,0,0.35)",
  },
  brand: {
    display:     "flex",
    alignItems:  "center",
    gap:         "12px",
    marginBottom: "28px",
    justifyContent: "center",
  },
  brandBar: {
    width:        "6px",
    height:       "32px",
    background:   "linear-gradient(180deg, #00e5a0, #0077ff)",
    borderRadius: "2px",
  },
  brandTitle: {
    fontSize:     "16px",
    fontWeight:   700,
    letterSpacing: "0.18em",
    color:        "#e8f4ff",
  },
  brandSub: {
    fontSize:     "9px",
    color:        "#8899aa",
    letterSpacing: "0.22em",
    marginTop:    "2px",
  },
  pageTitle: {
    fontSize:     "13px",
    fontWeight:   700,
    color:        "#00e5a0",
    letterSpacing: "0.12em",
    textAlign:    "center",
    marginBottom: "24px",
  },
  label: {
    display:    "block",
    fontSize:   "10px",
    color:      "#8899aa",
    letterSpacing: "0.12em",
    marginBottom: "6px",
    marginTop:    "14px",
  },
  input: {
    width:      "100%",
    background: "#070d18",
    border:     "1px solid #1d2638",
    borderRadius: "3px",
    color:      "#e8f4ff",
    padding:    "10px 12px",
    fontSize:   "13px",
    fontFamily: "inherit",
    outline:    "none",
    boxSizing:  "border-box",
  },
  inputError: {
    border: "1px solid #ff4d6d",
  },
  button: {
    width:      "100%",
    marginTop:  "24px",
    background: "#001a0e",
    border:     "1px solid #00e5a0",
    borderRadius: "3px",
    color:      "#00e5a0",
    padding:    "12px 16px",
    fontSize:   "12px",
    cursor:     "pointer",
    fontFamily: "inherit",
    letterSpacing: "0.12em",
    fontWeight: 600,
  },
  buttonDisabled: {
    opacity:    0.5,
    cursor:     "not-allowed",
  },
  error: {
    background: "rgba(255, 77, 109, 0.08)",
    border:     "1px solid #ff4d6d",
    borderRadius: "3px",
    color:      "#ff4d6d",
    fontSize:   "11px",
    padding:    "10px 12px",
    marginTop:  "16px",
    textAlign:  "center",
  },
  success: {
    background: "rgba(0, 229, 160, 0.08)",
    border:     "1px solid #00e5a0",
    borderRadius: "3px",
    color:      "#00e5a0",
    fontSize:   "12px",
    padding:    "14px 16px",
    marginTop:  "16px",
    textAlign:  "center",
    lineHeight: 1.5,
  },
  linkRow: {
    marginTop:    "20px",
    fontSize:     "11px",
    color:        "#8899aa",
    textAlign:    "center",
    display:      "flex",
    flexDirection: "column",
    gap:          "8px",
  },
  link: {
    color:           "#0099ff",
    textDecoration:  "none",
    cursor:          "pointer",
    background:      "none",
    border:          "none",
    fontFamily:      "inherit",
    fontSize:        "11px",
    padding:         0,
  },
};
