"""initial_schema

Revision ID: aa2d62ea88e4
Revises: 
Create Date: 2026-03-24 21:57:52.138940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2d62ea88e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iv_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('iv_date', sa.String(), nullable=False),
    sa.Column('implied_vol', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'iv_date', name='uix_iv_history_ticker_date')
    )
    op.create_index('ix_iv_history_ticker_date', 'iv_history', ['ticker', 'iv_date'], unique=False)
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('yahoo_symbol', sa.String(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('ma50', sa.Float(), nullable=True),
    sa.Column('ma100', sa.Float(), nullable=True),
    sa.Column('rel_iv', sa.Integer(), nullable=True),
    sa.Column('spark_json', sa.Text(), nullable=True),
    sa.Column('history_json', sa.Text(), nullable=True),
    sa.Column('history_dates_json', sa.Text(), nullable=True),
    sa.Column('volume_history_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cache_date', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('iv_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_cache_id'), 'price_cache', ['id'], unique=False)
    op.create_index(op.f('ix_price_cache_ticker'), 'price_cache', ['ticker'], unique=False)
    op.create_table('scheduler_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('refresh_ok', sa.Boolean(), nullable=True),
    sa.Column('signals_ok', sa.Boolean(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_log_run_date'), 'scheduler_log', ['run_date'], unique=False)
    op.create_table('schwab_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('lrr', sa.Float(), nullable=True),
    sa.Column('hrr', sa.Float(), nullable=True),
    sa.Column('structural_state', sa.String(), nullable=True),
    sa.Column('trade_direction', sa.String(), nullable=True),
    sa.Column('conviction', sa.Float(), nullable=True),
    sa.Column('h_value', sa.Float(), nullable=True),
    sa.Column('viewpoint', sa.String(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=True),
    sa.Column('vol_signal', sa.String(), nullable=True),
    sa.Column('warning', sa.Boolean(), nullable=True),
    sa.Column('lrr_warn', sa.Boolean(), nullable=True),
    sa.Column('hrr_warn', sa.Boolean(), nullable=True),
    sa.Column('pivot_b', sa.Float(), nullable=True),
    sa.Column('pivot_c', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_history_date_ticker', 'signal_history', ['snapshot_date', 'ticker'], unique=False)
    op.create_index(op.f('ix_signal_history_snapshot_date'), 'signal_history', ['snapshot_date'], unique=False)
    op.create_table('signal_hurst',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('h_trade', sa.Float(), nullable=True),
    sa.Column('h_trend', sa.Float(), nullable=True),
    sa.Column('h_lt', sa.Float(), nullable=True),
    sa.Column('d_trade', sa.Float(), nullable=True),
    sa.Column('d_trend', sa.Float(), nullable=True),
    sa.Column('d_lt', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_signal_hurst_ticker'), 'signal_hurst', ['ticker'], unique=False)
    op.create_table('signal_output',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('lrr', sa.Float(), nullable=True),
    sa.Column('hrr', sa.Float(), nullable=True),
    sa.Column('structural_state', sa.String(), nullable=True),
    sa.Column('trade_direction', sa.String(), nullable=True),
    sa.Column('conviction', sa.Float(), nullable=True),
    sa.Column('h_value', sa.Float(), nullable=True),
    sa.Column('viewpoint', sa.String(), nullable=True),
    sa.Column('viewpoint_since', sa.Text(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=True),
    sa.Column('vol_signal', sa.String(), nullable=True),
    sa.Column('warning', sa.Boolean(), nullable=True),
    sa.Column('lrr_warn', sa.Boolean(), nullable=True),
    sa.Column('hrr_warn', sa.Boolean(), nullable=True),
    sa.Column('pivot_b', sa.Float(), nullable=True),
    sa.Column('pivot_c', sa.Float(), nullable=True),
    sa.Column('obv_direction', sa.String(), nullable=True),
    sa.Column('obv_confirming', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timeframe', name='uq_signal_output_ticker_timeframe')
    )
    op.create_index(op.f('ix_signal_output_ticker'), 'signal_output', ['ticker'], unique=False)
    op.create_table('signal_pivots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('bar_window', sa.Integer(), nullable=True),
    sa.Column('pivot_a', sa.Float(), nullable=True),
    sa.Column('pivot_b', sa.Float(), nullable=True),
    sa.Column('pivot_c', sa.Float(), nullable=True),
    sa.Column('pivot_d', sa.Float(), nullable=True),
    sa.Column('pivot_a_date', sa.String(), nullable=True),
    sa.Column('pivot_b_date', sa.String(), nullable=True),
    sa.Column('pivot_c_date', sa.String(), nullable=True),
    sa.Column('pivot_d_date', sa.String(), nullable=True),
    sa.Column('structural_state', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timeframe', name='uq_signal_pivots_ticker_timeframe')
    )
    op.create_index(op.f('ix_signal_pivots_id'), 'signal_pivots', ['id'], unique=False)
    op.create_index(op.f('ix_signal_pivots_ticker'), 'signal_pivots', ['ticker'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('parent_ticker', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_ticker'), 'tickers', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_ticker'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_signal_pivots_ticker'), table_name='signal_pivots')
    op.drop_index(op.f('ix_signal_pivots_id'), table_name='signal_pivots')
    op.drop_table('signal_pivots')
    op.drop_index(op.f('ix_signal_output_ticker'), table_name='signal_output')
    op.drop_table('signal_output')
    op.drop_index(op.f('ix_signal_hurst_ticker'), table_name='signal_hurst')
    op.drop_table('signal_hurst')
    op.drop_index(op.f('ix_signal_history_snapshot_date'), table_name='signal_history')
    op.drop_index('ix_signal_history_date_ticker', table_name='signal_history')
    op.drop_table('signal_history')
    op.drop_table('schwab_tokens')
    op.drop_index(op.f('ix_scheduler_log_run_date'), table_name='scheduler_log')
    op.drop_table('scheduler_log')
    op.drop_index(op.f('ix_price_cache_ticker'), table_name='price_cache')
    op.drop_index(op.f('ix_price_cache_id'), table_name='price_cache')
    op.drop_table('price_cache')
    op.drop_index('ix_iv_history_ticker_date', table_name='iv_history')
    op.drop_table('iv_history')
    # ### end Alembic commands ###
